import { integer, primaryKey, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const agents = sqliteTable("agents", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  displayName: text("display_name").notNull(),
  persona: text("persona").notNull(),
  background: text("background").notNull(),
  greeting: text("greeting").notNull(),
  speakingStyle: text("speaking_style").notNull(),
  hobbiesJson: text("hobbies_json").notNull().default("[]"),
  worldId: text("world_id").notNull().default("default"),
  status: text("status").notNull().default("active"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const worlds = sqliteTable("worlds", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  lore: text("lore").notNull().default(""),
  tone: text("tone").notNull().default(""),
  constraintsJson: text("constraints_json").notNull().default("[]"),
  seedMemoriesJson: text("seed_memories_json").notNull().default("[]"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const conversations = sqliteTable("conversations", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  agentId: text("agent_id").notNull(),
  worldId: text("world_id").notNull().default("default"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const messages = sqliteTable("messages", {
  id: text("id").primaryKey(),
  conversationId: text("conversation_id").notNull(),
  role: text("role").notNull(),
  content: text("content").notNull(),
  metadataJson: text("metadata_json").notNull().default("{}"),
  createdAt: integer("created_at").notNull(),
});

export const memories = sqliteTable("memories", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  agentId: text("agent_id").notNull(),
  worldId: text("world_id").notNull().default("default"),
  subject: text("subject").notNull(),
  memoryType: text("memory_type").notNull(),
  content: text("content").notNull(),
  importance: real("importance").notNull().default(0.5),
  confidence: real("confidence").notNull().default(0.5),
  status: text("status").notNull().default("active"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
  accessCount: integer("access_count").notNull().default(0),
  lastAccessedAt: integer("last_accessed_at"),
  canonicalKey: text("canonical_key"),
  topic: text("topic"),
  embeddingJson: text("embedding_json"),
  embeddingModel: text("embedding_model"),
  embeddingBackend: text("embedding_backend"),
  embeddingQuality: text("embedding_quality"),
  embeddingDimension: integer("embedding_dimension"),
  embeddingStatus: text("embedding_status").notNull().default("missing"),
  embeddingTextHash: text("embedding_text_hash"),
  embeddingVersion: integer("embedding_version").notNull().default(1),
  embeddingNeedsRefresh: integer("embedding_needs_refresh").notNull().default(1),
  embeddingUpdatedAt: integer("embedding_updated_at"),
  supersededBy: text("superseded_by"),
  supersededReason: text("superseded_reason"),
  lastObservedAt: integer("last_observed_at"),
  sourceMessageId: text("source_message_id"),
  sourceTaskId: text("source_task_id"),
});

export const agentLiveStates = sqliteTable(
  "agent_live_states",
  {
    agentId: text("agent_id").notNull(),
    userId: text("user_id").notNull(),
    agentName: text("agent_name").notNull(),
    moodLabel: text("mood_label").notNull(),
    moodIntensity: real("mood_intensity").notNull(),
    heartbeatBpm: integer("heartbeat_bpm").notNull(),
    riskLevel: text("risk_level").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (table) => [primaryKey({ columns: [table.userId, table.agentId] })],
);

export const feedPosts = sqliteTable("feed_posts", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  agentId: text("agent_id").notNull(),
  agentName: text("agent_name").notNull(),
  worldId: text("world_id").notNull().default("default"),
  content: text("content").notNull(),
  topicSeed: text("topic_seed").notNull(),
  postType: text("post_type").notNull().default("status"),
  status: text("status").notNull().default("published"),
  sourceTaskId: text("source_task_id"),
  createdAt: integer("created_at").notNull(),
});

export const tasks = sqliteTable("tasks", {
  id: text("id").primaryKey(),
  kind: text("kind").notNull(),
  payloadJson: text("payload_json").notNull().default("{}"),
  status: text("status").notNull().default("pending"),
  attempts: integer("attempts").notNull().default(0),
  lastError: text("last_error"),
  runAfter: integer("run_after").notNull().default(0),
  idempotencyKey: text("idempotency_key"),
  lockedBy: text("locked_by"),
  lockedAt: integer("locked_at"),
  lockExpiresAt: integer("lock_expires_at"),
  maxAttempts: integer("max_attempts").notNull().default(3),
  nextAttemptAt: integer("next_attempt_at"),
  completedAt: integer("completed_at"),
  failedPermanentlyAt: integer("failed_permanently_at"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const memoriesFts = sqliteTable("memories_fts", {
  rowid: integer("rowid").notNull(),
  content: text("content").notNull(),
});

export const memoryOperationLogs = sqliteTable("memory_operation_logs", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  agentId: text("agent_id").notNull(),
  worldId: text("world_id").notNull(),
  kind: text("kind").notNull(),
  reason: text("reason").notNull(),
  detail: text("detail"),
  sourceTaskId: text("source_task_id"),
  createdAt: integer("created_at").notNull(),
});

export const feedTopics = sqliteTable("feed_topics", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  worldId: text("world_id").notNull(),
  agentId: text("agent_id").notNull().default("__shared__"),
  topicKey: text("topic_key").notNull(),
  representativeEmbeddingJson: text("representative_embedding_json").notNull(),
  embeddingModel: text("embedding_model").notNull(),
  embeddingQuality: text("embedding_quality").notNull(),
  embeddingDimension: integer("embedding_dimension").notNull(),
  useCount: integer("use_count").notNull().default(1),
  firstSeenAt: integer("first_seen_at").notNull(),
  lastUsedAt: integer("last_used_at").notNull(),
});

export const worldEvents = sqliteTable("world_events", {
  id: text("id").primaryKey(),
  decisionId: text("decision_id").notNull(),
  worldRunId: text("world_run_id").notNull(),
  userId: text("user_id").notNull(),
  worldId: text("world_id").notNull(),
  tick: integer("tick").notNull(),
  sequence: integer("sequence").notNull(),
  schemaVersion: integer("schema_version").notNull().default(1),
  reducerVersion: integer("reducer_version").notNull().default(1),
  type: text("type").notNull(),
  payloadJson: text("payload_json").notNull(),
  summary: text("summary").notNull(),
  visibility: text("visibility").notNull(),
  visibleToActorIdsJson: text("visible_to_actor_ids_json").notNull().default("[]"),
  visibleToUser: integer("visible_to_user").notNull().default(0),
  actorIdsJson: text("actor_ids_json").notNull().default("[]"),
  locationKey: text("location_key"),
  causedByEventId: text("caused_by_event_id"),
  causedByUserActionId: text("caused_by_user_action_id"),
  idempotencyKey: text("idempotency_key").notNull(),
  status: text("status").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const worldStateSnapshots = sqliteTable("world_state_snapshots", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  worldId: text("world_id").notNull(),
  tick: integer("tick").notNull(),
  snapshotKind: text("snapshot_kind").notNull().default("latest"),
  isLatest: integer("is_latest").notNull().default(0),
  appliedEventSequence: integer("applied_event_sequence").notNull(),
  appliedEventIdsJson: text("applied_event_ids_json").notNull(),
  reducerVersion: integer("reducer_version").notNull(),
  stateJson: text("state_json").notNull(),
  checksum: text("checksum"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

// WorldMind phase 2: retry envelopes
export const worldRuns = sqliteTable("world_runs", {
  id: text("id").primaryKey(),
  idempotencyKey: text("idempotency_key").notNull(),
  userId: text("user_id").notNull(),
  worldId: text("world_id").notNull(),
  sourceType: text("source_type").notNull(),
  sourceActionId: text("source_action_id").notNull(),
  decisionId: text("decision_id").notNull(),
  agentId: text("agent_id"),
  status: text("status").notNull(),
  resultJson: text("result_json"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

// WorldMind phase 2: per-actor character state
export const characterStates = sqliteTable("character_states", {
  userId: text("user_id").notNull(),
  worldId: text("world_id").notNull(),
  agentId: text("agent_id").notNull(),
  locationKey: text("location_key").notNull(),
  currentGoal: text("current_goal").notNull(),
  emotionalStateJson: text("emotional_state_json").notNull(),
  relationshipToUserJson: text("relationship_to_user_json").notNull(),
  knowledgeKeysJson: text("knowledge_keys_json").notNull().default("[]"),
  activeCommandId: text("active_command_id"),
  lastActedAt: integer("last_acted_at"),
  updatedAt: integer("updated_at").notNull(),
});

// WorldMind phase 2: command queue
export const actorCommands = sqliteTable("actor_commands", {
  id: text("id").primaryKey(),
  decisionId: text("decision_id").notNull(),
  worldRunId: text("world_run_id").notNull(),
  userId: text("user_id").notNull(),
  worldId: text("world_id").notNull(),
  targetAgentId: text("target_agent_id").notNull(),
  commandType: text("command_type").notNull(),
  priority: text("priority").notNull(),
  visibility: text("visibility").notNull(),
  visibleToActorIdsJson: text("visible_to_actor_ids_json").notNull().default("[]"),
  visibleToUser: integer("visible_to_user").notNull().default(0),
  actorInstruction: text("actor_instruction").notNull(),
  privateReason: text("private_reason"),
  causeJson: text("cause_json").notNull(),
  payloadJson: text("payload_json").notNull().default("{}"),
  relatedEventId: text("related_event_id"),
  status: text("status").notNull(),
  runAfter: integer("run_after").notNull(),
  expiresAt: integer("expires_at"),
  idempotencyKey: text("idempotency_key").notNull(),
  claimedBy: text("claimed_by"),
  claimedAt: integer("claimed_at"),
  claimExpiresAt: integer("claim_expires_at"),
  resultEventId: text("result_event_id"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

// WorldMind phase 2: decision audit log
export const worldDecisionLogs = sqliteTable("world_decision_logs", {
  id: text("id").primaryKey(),
  decisionId: text("decision_id").notNull(),
  worldRunId: text("world_run_id").notNull(),
  userId: text("user_id").notNull(),
  worldId: text("world_id").notNull(),
  sourceType: text("source_type").notNull(),
  sourceEventId: text("source_event_id"),
  sourceTaskId: text("source_task_id"),
  modelProvider: text("model_provider").notNull(),
  modelName: text("model_name").notNull(),
  promptContextHash: text("prompt_context_hash").notNull(),
  rawDecisionJson: text("raw_decision_json"),
  validatedDecisionJson: text("validated_decision_json"),
  validationStatus: text("validation_status").notNull(),
  validationErrorsJson: text("validation_errors_json").notNull().default("[]"),
  errorCode: text("error_code"),
  errorMessage: text("error_message"),
  createdEventIdsJson: text("created_event_ids_json").notNull().default("[]"),
  createdCommandIdsJson: text("created_command_ids_json").notNull().default("[]"),
  createdAt: integer("created_at").notNull(),
});

// WorldMind phase 2: persistent world memories
export const worldMemories = sqliteTable("world_memories", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  worldId: text("world_id").notNull(),
  subjectType: text("subject_type").notNull(),
  subjectKey: text("subject_key").notNull(),
  memoryType: text("memory_type").notNull(),
  canonicalKey: text("canonical_key"),
  content: text("content").notNull(),
  visibility: text("visibility").notNull(),
  visibleToActorIdsJson: text("visible_to_actor_ids_json").notNull().default("[]"),
  visibleToUser: integer("visible_to_user").notNull().default(0),
  importance: real("importance").notNull().default(0.5),
  confidence: real("confidence").notNull().default(0.5),
  validFromTick: integer("valid_from_tick").notNull().default(0),
  sourceEventId: text("source_event_id"),
  sourceDecisionId: text("source_decision_id"),
  supersededBy: text("superseded_by"),
  embeddingJson: text("embedding_json"),
  embeddingQuality: text("embedding_quality"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const worldSummaries = sqliteTable("world_summaries", {
  id: text("id").primaryKey(),
  userId: text("user_id").notNull(),
  worldId: text("world_id").notNull(),
  summaryScope: text("summary_scope").notNull(),
  subjectType: text("subject_type").notNull(),
  subjectKey: text("subject_key").notNull(),
  content: text("content").notNull(),
  visibility: text("visibility").notNull(),
  visibleToActorIdsJson: text("visible_to_actor_ids_json").notNull().default("[]"),
  visibleToUser: integer("visible_to_user").notNull().default(0),
  sourceEventSequenceFrom: integer("source_event_sequence_from").notNull(),
  sourceEventSequenceTo: integer("source_event_sequence_to").notNull(),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});
